---
name: Design Proposal
description: Suggest a new design approach or layout idea
title: "[Design Proposal] "
labels: ["design", "proposal"]
assignees: []
---

## ✨ Proposal Summary

Give a short overview of your design idea.

## 🧩 What problem does this solve?

Explain the current limitation and how your proposal improves it.

## 📸 Visuals / Mockups

Add designs, sketches, or screenshot comparisons to show your vision.
