---
name: Design Improvement
description: Report a design issue or UI/UX improvement idea
title: "[Design Improvement] "
labels: ["design", "help wanted"]
assignees: []
---

## 🧠 What needs improvement?

Please describe the UI or UX issue you found and why it should be improved.

## 🎨 Proposed change

Explain how you think the design can be improved.  
Include screenshots, mockups, or Figma/Sketch links if available.

## 📸 Screenshots / Examples

If possible, add visuals to support your suggestion.
